# -*- coding: utf-8 -*-
"""anas1006.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qu23iZaM5n6rGmBR4Kdb4rfwZcqmlpe
"""

num1 = int (input())
num2 = int (input())
if (num1>num2):
  print("num1 is largest ")
else:
  print("num2 is largest")

num = int(input())
fact = 1
for i in range(1, num + 1):
  fact *= i
print("factorial is: ", fact)

a = int(input("Enter the first number:"))
b = int(input("Enter the seconde number:"))

x = a
y = b
while b != 0:
  a, b = b, a % b

  gcd = a

  lcm = (a * b ) // gcd

  print("GCD =", gcd)
  print("LCM =", lcm)

num =[3, 17, 29, 7, 65, 92]
largest = max(num)
smallest = min(num)
print(largest)
print(smallest)

a=int(input("enter first number"))
b=int(input("enter the seconde number"))
print("Add=",a+b)
print("Sub=",a-b)
print("Mul=",a*b)
print("Div=",a%b)

text= input()
vowels="a e i o u "
count=0

for ch in  text:
  if ch in vowels:
    print(ch)
    count+=1
    print(count)

a = int (input())
length =len(str(a))
s=0
t=a
while(t>0)
d=t%10
s+=d**length
t=t//10
if (s==a)
  print("armstrong")
else:
  print("not armstrong")

a=int(input())
b=int(input())
c=int(input())
avg=(a+b+c)/3
print(avg)

for num in range(1, 51):

   if num > 1:
      for i in range(2, num):
          if num % i == 0:
             break
       else:
           print(num)

a= int(input())
b= int(input())
a,b=b,a
print(a)
print(b)

n =int (input())
a,b=0,1
for i in range(n):
  print(a)
  a,b = b,a+b

text = input()
if (text==text[::-1]):
  print ("it is palindrome")
else:
  print("not palindrome")

n = int (input())
c=float(input())
F=(c*9/5) + 32
print(f)

n=int(input())
if n>0:
  print("positive")
elif n<0:
  print("negative")
else:
  print("zero")

x=int(input())
if x%4==0:
  print("leapyear")
else:
  print("not leapyear")

x=int(input())
if x%2==0:
  print("even")
else:
  print("odd")

s1=input()
s2=input()
if sorted (s1)==sorted(s2):
  print("anagram")
else:
  print("not anagram")

for i in range(1,6):
  for j in range(1,i+1):
    print(j,end="")
  print()

n=6
for i in range(n):
  print(" "*i+"*"*(n-1))

n = 3
for i in range(1,n+1):
  print(" " * (n -i ) + "* " * i)
for i in range(n-1,0,-1):
  print(" " * (n-i) + "* " * i )

n=int(input())
for i in range(1,n+1):
  print (" " * (n-i) + "* " * i)

a=[20,40,50,10,30]
largest = sorted(a,reverse = true)[:3]
print(largest)

import math
a=int(input())
if math.sqt(a):
  print("power of 2")
else:
  print("not")

s1=input()
s2=input()
if s1==s2,s2==s1:
  print("anagram")
else:
  print("not anagram")

name = "Anas"
marks = [78, 45, 92, 30, 67]

total = sum(marks)
average = total / len(marks)
highest = max(marks)

if min(marks) >= 35:
    status = "Pass"
else:
    status = "Fail"

print("Total:", total)
print("Average:", average)
print("Highest Mark:", highest)
print("Status:", status)

name = input("Employee Name: ")

scores = [75, 82, 90, 65, 88, 70]

print("Best Score:", max(scores))
print("Average Score:", sum(scores)/len(scores))

count = 0
for i in scores:
    if i > 80:
        count += 1

print("Months Above 80:", count)

class ParkingLot:
    def __init__(self, v):
        self.v = v

    def show(self):
        d = []

        for i in self.v:
            if self.v.count(i) > 1 and i not in d:
                d.append(i)

        print("Duplicate Vehicles:", d)
        print("Unique Vehicles:", len(set(self.v)))


v = [101, 105, 110, 101, 115, 105]

p = ParkingLot(v)
p.show()