# -*- coding: utf-8 -*-
"""netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OioQezsBRZq08drc05uQmNIlZEi5DwY
"""

import os
os.environ['KAGGLE_USERNAME']='ariyansmart'
os.environ['KAGGLE_KEY']='KGAT_2f40c6c1d816c98f44930fcc8c256f4d'

!pip install kaggle

!kaggle datasets download -d 'paramvir705/netflix-dataset'

!unzip netflix-dataset.zip

import pandas as pd
df = pd.read_csv("netflix-dataset.zip")
df.head(10)

print(len(df))
print(df.shape)

df.info()

df.duplicated().sum()

df.dtypes

df.columns

df.drop

df.isnull().sum()

df["show_id"].fillna(df["show_id"],inplace=True)
print(df[["show_id"]].head(10))
print(df[["show_id"]].isnull().sum())

df.drop_duplicates(inplace=True)
print(df)

df['type'] = df['type'].map({'Movie':0,'Tv show':1})
print(df)

!kaggle datasets download -d 'paramvir705/netflix-dataset'

!unzip netflix-dataset.zip

import pandas as pd
df = pd.read_csv("netflix-dataset.zip")
df.head(10)

df.tail(10)

df.duplicated().sum()

df.dtypes

df.info

df.describe()

df.columns

df.drop

df.isnull().sum()

df['show_id'].fillna(df['show_id'], inplace = True)
print(df[['show_id']].head(10))
print(df[['show_id']].isnull().sum())

df.drop_duplicates(inplace=True)
print(df)

df['type'] = df['type'].map({'Movie':0,'TV Show':1})
print(df)

df['content_age'] = 2026 - df['release_year']

print(df[['title', 'release_year', 'content_age']].head())

print(df.columns)

df.drop('description', axis=1, inplace=True)
print(df.columns)

df['director']=df['director'].fillna('unknown')

df['cast']=df['cast'].fillna('unknown')

df['country']=df['country'].fillna('unknown')

df['date_added']=df['date_added'].fillna('unknown')

df['rating']=df['rating'].fillna('unknown')

df['duration']=df['duration'].fillna('unknown')

df.isnull().sum()

import matplotlib.pyplot as plt
plt.boxplot(df['release_year'])
plt.title('outlier Detection using Boxplot(release_year)')
plt.ylabel('release_year')
plt.show()

plt.scatter(df.index, df['release_year'])
plt.title('scatter plot (release_year)')
plt.xlabel('index')
plt.ylabel('release_year')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X = df[['release_year']]
y = df['type']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
print("Model Trained")
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy:.5f}")
print(f"Confusion Matrix:\n{cm}")
print(f"Classification Report:\n{report}")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
df = pd.read_csv("netflix_titles.csv")
df = df.drop(['show_id', 'title', 'director', 'cast',
              'country', 'date_added', 'description'],
             axis=1, errors='ignore')
df = df.fillna("Unknown")
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])
y = df['release_year']
X = df.drop('release_year', axis=1)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LinearRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, pred))
print("MSE:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))
print("Model trained successfully")